server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true

spring:
  application:
    name: apigateway-sub-service
  cloud:
    gateway:
      routes:
        - id: openapi
          uri: lb://${spring.application.name}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
#        - id: openapi/first-service-test
#          uri: lb://FIRST-SERVICE
#          predicates:
#            - Path=/openapi/first-service/**, /first-service/**
#          filters:
#            - RewritePath=/openapi/first-service/(?<path>.*), /$\{path}
#            - CustomFilter
#            - name: LoggingFilter
#              args:
#                baseMessage: Spring Cloud Gateway Logging Filter
#                preLogger: true
#                postLogger: true
        - id: backend/user-service
          uri: lb://BACKEND-USER
          predicates:
            - Path=/backend/user/**, /user/**
          filters:
            - RewritePath=/backend/user/(?<path>.*), /$\{path}
            - CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway Logging Filter
                preLogger: true
                postLogger: true
        - id: backend/simul-service
          uri: lb://BACKEND-SIMUL
          predicates:
            - Path=/simul/**, /backend/simul/**
          filters:
            - RewritePath=/backend/simul/(?<path>.*), /$\{path}
            - CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway Logging Filter
                preLogger: true
                postLogger: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
  main:
    web-application-type: reactive

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
