server:
  port: 8081
spring:
  application:
    name: apigateway-sub-service
  cloud:
    gateway:
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: backend-user-service
          uri: lb://BACKEND-USER
          predicates:
            - Path=/user/**, /backend-user/user/**
          filters:
            - RewritePath=/backend-user/user/(?<path>.*), /$\{path}
            - CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway Logging Filter
                preLogger: true
                postLogger: true
        - id: backend-simul-service
          uri: lb://BACKEND-SIMUL
          predicates:
            - Path=/simul/**, /backend-simul/simul/**
          filters:
            - RewritePath=/backend-simul/simul/(?<path>.*), /$\{path}
            - CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway Logging Filter
                preLogger: true
                postLogger: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
  main:
    web-application-type: reactive

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
